# Generated by Django 5.2.5 on 2025-08-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_lanzamiento", models.DateField()),
                ("puntuacion", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
