# Generated by Django 5.2.5 on 2025-08-11 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pelicula",
            name="fecha_lanzamiento",
        ),
        migrations.AddField(
            model_name="pelicula",
            name="año_lanzamiento",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1888),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="director",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="pelicula",
            name="genero",
            field=models.CharField(
                choices=[
                    ("accion", "Acción"),
                    ("drama", "Drama"),
                    ("comedia", "Comedia"),
                    ("terror", "Terror"),
                    ("romance", "Romance"),
                    ("documental", "Documental"),
                    ("animacion", "Animación"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="puntuacion",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
