# Generated by Django 5.2.5 on 2025-08-11 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_pelicula_fecha_lanzamiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="peliculas/"),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="año_lanzamiento",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1850),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="genero",
            field=models.CharField(
                choices=[
                    ("accion", "Acción"),
                    ("drama", "Drama"),
                    ("comedia", "Comedia"),
                    ("terror", "Terror"),
                    ("romance", "Romance"),
                    ("documental", "Documental"),
                    ("animacion", "Animación"),
                    ("ciencia_ficcion", "Ciencia Ficción"),
                    ("fantasia", "Fantasía"),
                    ("aventura", "Aventura"),
                    ("musical", "Musical"),
                    ("biografia", "Biografía"),
                    ("historia", "Historia"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
    ]
