# Generated by Django 5.2.5 on 2025-08-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_pelicula_imagen_alter_pelicula_año_lanzamiento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pelicula",
            old_name="año_lanzamiento",
            new_name="anio_lanzamiento",
        ),
    ]
