# Generated by Django 5.2.5 on 2025-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_pelicula_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="genero",
            field=models.CharField(
                choices=[
                    ("accion", "Acción"),
                    ("animacion", "Animación"),
                    ("aventura", "Aventura"),
                    ("biografia", "Biografía"),
                    ("ciencia_ficcion", "Ciencia Ficción"),
                    ("comedia", "Comedia"),
                    ("crimen", "Crimen"),
                    ("deporte", "Deporte"),
                    ("documental", "Documental"),
                    ("drama", "Drama"),
                    ("fantasia", "Fantasía"),
                    ("guerra", "Guerra"),
                    ("historia", "Historia"),
                    ("misterio", "Misterio"),
                    ("musical", "Musical"),
                    ("romance", "Romance"),
                    ("superheroes", "Superhéroes"),
                    ("suspenso", "Suspenso"),
                    ("terror", "Terror"),
                    ("thriller", "Thriller"),
                    ("western", "Western"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
    ]
