# Generated by Django 5.2.5 on 2025-08-13 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_pelicula_puntuacion_profile_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="puntuacion",
            field=models.DecimalField(
                decimal_places=1,
                default=3.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
