# Generated by Django 5.2.5 on 2025-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_pelicula_puntuacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
